---

version: "3.8"

services:
  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres:
